// Content data for the AI Research Agent case study.
// Keep all editable copy here so section files stay focused on layout.

const PROBLEM_CARDS = [
  {
    icon: 'refresh-cw',
    title: 'Repeated manual research',
    description: 'Opening several pages, collecting relevant details and writing an analysis for one company at a time — then repeating the same process for the next one.',
  },
  {
    icon: 'shuffle',
    title: 'Inconsistent output',
    description: 'When research is done manually, every write-up looks different. That makes results harder to compare, review or hand off to someone else.',
  },
  {
    icon: 'file-question',
    title: 'Generic AI output',
    description: 'AI-generated text can sound thorough while saying nothing specific. A quality check step is the only reliable way to catch output that is too general to act on.',
  },
];

const SOLUTION_FLOW = [
  'Company queued in Supabase',
  'Website content retrieved via HTTP',
  'Company analysis generated by Groq',
  'Quality checked by a second Groq call',
  'Approved or held for improvement',
  'Final master report generated and saved',
];

const SCENARIOS = [
  {
    tag: 'Scenario 1',
    title: 'Company Analysis',
    description:
      'Finds a queued company in Supabase and immediately marks it as processing — this lock prevents the same record from being picked up twice if the scenario runs again. The HTTP module retrieves website content, which Groq then analyses and returns as structured JSON. The result and status are saved back to Supabase.',
    flow: ['Queued company', 'Locked as processing', 'Website content via HTTP', 'Groq analysis', 'Saved as analyzed'],
    highlight: false,
  },
  {
    tag: 'Scenario 2',
    title: 'Quality Check',
    description:
      'Finds an analyzed record and locks it as quality_checking before doing anything else. A second Groq call evaluates whether the analysis is specific and useful or too generic. The Make.com router reads the structured JSON response and routes to the correct branch — Make decides the next step, not the AI.',
    routes: [
      { label: 'Approved', tone: 'success', text: 'Status set to approved. Scenario 3 picks it up for the final report.' },
      { label: 'Needs improvement', tone: 'warning', text: 'Feedback is saved and status set to needs_improvement. The analysis does not continue.' },
    ],
    highlight: true,
  },
  {
    tag: 'Scenario 3',
    title: 'Final Master Report',
    description:
      'Finds an approved record and locks it as report_generating. Groq generates the final structured master report from the approved analysis. The report and final status are saved to Supabase. The pipeline is complete for that company.',
    flow: ['Approved analysis', 'Locked as report_generating', 'Groq master report', 'Saved as final'],
    highlight: false,
  },
];

const TOO_GENERIC = [
  'Repeats information that appears on every company website',
  'Lacks company-specific observations or context',
  'Sounds useful but gives nothing concrete to act on',
  'Does not continue to the final report',
];

const READY_TO_APPROVE = [
  'Uses specific information from the company website',
  'Includes observations that go beyond the obvious',
  'Follows the expected structure',
  'Clear enough to be useful in the final report',
];

const TOOLS = [
  { label: 'Make.com', icon: 'workflow', color: '#7A2FF8', description: 'Connects and controls all three scenarios. Make routes records between states based on Groq output — the routing logic is deterministic, not AI.' },
  { label: 'Supabase', icon: 'database', color: '#3ECF8E', description: 'Stores company records, analyses, quality feedback, final reports and workflow statuses. The status field is the handoff mechanism between scenarios.' },
  { label: 'HTTP', icon: 'globe', color: '#3B82C4', description: 'Retrieves content from the company website. Groq cannot open a URL on its own — the HTTP module does it and passes the content forward.' },
  { label: 'Groq', icon: 'cpu', color: '#F0662A', description: 'Used in three steps: generating the company analysis, evaluating its quality and creating the final report. Each call uses a structured prompt and returns JSON.' },
];

const WORKFLOW_STATES = [
  'queued',
  'processing',
  'analyzed',
  'quality_checking',
  'approved',
  'needs_improvement',
  'report_generating',
  'final',
];

const WORKFLOW_STATE_DESCRIPTIONS = {
  queued: 'Company is waiting to be picked up by Scenario 1.',
  processing: 'Scenario 1 has locked the record and is retrieving website content.',
  analyzed: 'Groq has generated the analysis. Ready for Scenario 2.',
  quality_checking: 'Scenario 2 has locked the record and is evaluating quality.',
  approved: 'Quality check passed. Ready for Scenario 3.',
  needs_improvement: 'Analysis was too generic. Feedback saved. Does not continue.',
  report_generating: 'Scenario 3 has locked the record and is generating the master report.',
  final: 'Master report saved. Pipeline complete for this company.',
};

const LIMITATIONS = [
  'AI output can still contain weak or incorrect conclusions even after the quality check.',
  'Website content may be incomplete, require JavaScript to load or block automated retrieval.',
  'The quality check reduces generic output but does not replace human review before the report is used.',
  'The record-locking mechanism prevents most duplicate runs but is not a guaranteed safeguard in every edge case.',
  'Production use would require stronger error handling, retry logic, source tracking and monitoring.',
  'This is a portfolio demonstration tested with demonstration data, not a production deployment.',
];

const NEXT_IMPROVEMENTS = [
  'Add multi-source research using a search API alongside the company website',
  'Include source references so every claim can be traced back to where it came from',
  'Add retry and error handling for failed HTTP requests or Groq calls',
  'Build a human review step before the final report is marked as complete',
  'Test with a broader range of company websites including those with restricted content',
  'Add conflict detection when external sources contradict the company website',
];

const HERO_STAGES = [
  { label: 'Collect', detail: 'Website content retrieved via HTTP' },
  { label: 'Analyse', detail: 'Groq generates structured company analysis' },
  { label: 'Check', detail: 'Second Groq call evaluates quality' },
  { label: 'Report', detail: 'Approved analyses become final master reports' },
];

const LEARNED = {
  quote: 'Generating an answer is only one part of a useful AI workflow. The result also needs clear states, a separate review step and a way to handle output that is not good enough.',
  paragraph: 'I also learned why the record-locking step matters — marking a record as processing before doing anything else is what prevents two scenario runs from picking up the same company at the same time. And I learned the difference between AI making a decision and Make routing based on AI output. In Scenario 2, Groq returns a structured JSON value. The Make router reads that value and decides what happens next. The routing logic is deterministic. The AI just provides the input.',
  transparencyTitle: 'Project transparency',
  transparency1: 'This is a functional portfolio demonstration built and tested with demonstration data. It was not developed for a live client environment.',
  transparency2: 'The project demonstrates multi-scenario workflow design, state management, AI integration and quality control logic. It does not include measured client results.',
};

const AUTOMATION_TYPE = {
  label: 'AI automation — not agentic',
  description: 'Groq is used in three steps: company analysis, quality evaluation and final report generation. Make controls the flow and Supabase holds the state. This is AI automation because AI interpretation is the core of the system. It is not agentic automation because the AI does not decide its own next step — the Make router does that based on Groq\'s structured JSON output.',
};

window.CaseStudyContent = {
  HERO_STAGES,
  PROBLEM_CARDS,
  SOLUTION_FLOW,
  SCENARIOS,
  TOO_GENERIC,
  READY_TO_APPROVE,
  TOOLS,
  WORKFLOW_STATES,
  WORKFLOW_STATE_DESCRIPTIONS,
  LIMITATIONS,
  NEXT_IMPROVEMENTS,
  LEARNED,
  AUTOMATION_TYPE,
};
