// Bilingual workflow states, planned V2, learning, related work, CTA and footer.
const { Button, Callout } = window.MinaFlowDesignSystem_a5074e;
const { Icon, Shell, SectionHead, V2_PORTFOLIO_URL } = window;

const END_COPY = {
  en:{
    statesEy:'Workflow states & testing', statesTitle:'Every company moves through one connected lifecycle', statesLede:'The status field in Supabase is the handoff between scenarios — each scenario only picks up records in the state it is responsible for.', testingTitle:'Testing status', testing:'The three scenarios are technically working and the main routes were tested with demonstration data. The project was not deployed in a live client environment.', held:'held for improvement', final:'final outcome',
    plannedEy:"What's next for this project", plannedBadge:'PLANNED V2 — NOT IMPLEMENTED', plannedTitle:'Extending research beyond the company website', plannedText:'The current version mainly analyses information from a company’s official website. In a future V2, I plan to extend the workflow with multi-source research through a search API or similar service.', plannedNote:'These are planned future improvements and are not part of the current implemented version.',
    learnedEy:'What I learned', learnedQuote:'“Generating an answer is only one part of a useful AI workflow. The result also needs clear states, a separate review step and a way to handle output that is not good enough.”', learnedText:'I also learned how to connect website content, AI processing and database status changes across several Make.com scenarios.', transparency:'Project transparency', transparency1:'This is a functional portfolio demonstration built and tested with demonstration data. It was not developed for a live client environment.', transparency2:'AI-generated research should be reviewed before it is used for important business decisions.',
    relatedEy:'More case studies', relatedTitle:'Related work', c1:'Lead Capture Automation', c1Text:'Captures, validates and logs website leads, then sends an internal notification and automatic reply.', c2:'Order Handoff Automation', c2Text:'Turns a HubSpot Closed Won deal into a documented customer handoff with validation, duplicate prevention, welcome email and status logging.', action:'View Case Study',
    ctaEy:'Build with structure', ctaTitle:'Automation is more useful when the logic is clear.', ctaText:'This project shows how I approach AI automation: clear workflow states, controlled routing, a separate quality layer and transparent limitations.', ctaBtn:'Back to Portfolio', footer:'AI Research Agent · Portfolio demonstration'
  },
  sv:{
    statesEy:'Arbetsflödets statusar & testning', statesTitle:'Varje företag går genom en sammanhängande livscykel', statesLede:'Statusfältet i Supabase är överlämningen mellan scenarierna — varje scenario hämtar bara poster i den status det ansvarar för.', testingTitle:'Teststatus', testing:'De tre scenarierna fungerar tekniskt och huvudvägarna testades med demodata. Projektet har inte driftsatts i en live kundmiljö.', held:'hålls för förbättring', final:'slutresultat',
    plannedEy:'Nästa steg för projektet', plannedBadge:'PLANERAD V2 — INTE IMPLEMENTERAD', plannedTitle:'Utöka research utanför företagets webbplats', plannedText:'Den nuvarande versionen analyserar främst information från företagets officiella webbplats. I en framtida V2 planerar jag att utöka flödet med research från flera källor via en sök-API eller liknande tjänst.', plannedNote:'Detta är planerade framtida förbättringar och ingår inte i den nuvarande implementerade versionen.',
    learnedEy:'Vad jag lärde mig', learnedQuote:'“Att generera ett svar är bara en del av ett användbart AI-flöde. Resultatet behöver också tydliga statusar, ett separat granskningssteg och ett sätt att hantera output som inte är tillräckligt bra.”', learnedText:'Jag lärde mig också hur webbplatsinnehåll, AI-bearbetning och databasstatusar kan kopplas ihop över flera Make.com-scenarier.', transparency:'Projekttransparens', transparency1:'Detta är en fungerande portfoliodemonstration som byggts och testats med demodata. Den utvecklades inte för en live kundmiljö.', transparency2:'AI-genererad research bör granskas innan den används för viktiga affärsbeslut.',
    relatedEy:'Fler case studies', relatedTitle:'Relaterade projekt', c1:'Lead Capture Automation', c1Text:'Samlar in, validerar och loggar webbplatsleads och skickar sedan intern notis och automatiskt svar.', c2:'Order Handoff Automation', c2Text:'Förvandlar en HubSpot Closed Won-affär till en dokumenterad kundöverlämning med validering, dublettskydd, välkomstmejl och statusloggning.', action:'Visa Case Study',
    ctaEy:'Bygg med struktur', ctaTitle:'Automation blir mer användbar när logiken är tydlig.', ctaText:'Det här projektet visar hur jag arbetar med AI-automation: tydliga statusar, kontrollerad routing, ett separat kvalitetslager och transparenta begränsningar.', ctaBtn:'Tillbaka till Portfolio', footer:'AI Research Agent · Portfoliodemonstration'
  }
};

const LIFECYCLE=['queued','processing','analyzed','quality_checking','approved','needs_improvement','report_generating','final'];

function StatesSection(){const{lang}=window.useApp();const c=END_COPY[lang];return <Shell tone="ink" grid pad="lg" id="states"><SectionHead eyebrow={c.statesEy} title={c.statesTitle} lede={c.statesLede}/><div className="reveal-up panel-dark" style={{padding:'30px 26px',display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}>{LIFECYCLE.map((s,i)=><React.Fragment key={s}><span className={`state-pill ${s==='approved'?'good':s==='needs_improvement'?'warn':s==='final'?'final':''}`}>{s}</span>{i<LIFECYCLE.length-1&&<span style={{color:'var(--brand-300)'}}>→</span>}</React.Fragment>)}</div><div style={{marginTop:22,maxWidth:720}}><Callout kind="note" title={c.testingTitle}>{c.testing}</Callout></div></Shell>}

const PLANNED_EN=['Collect information from the official website and selected external sources.','Filter irrelevant and duplicate search results.','Keep the most useful sources for analysis.','Save source titles, URLs, dates and source types.','Connect important report claims with supporting sources.','Flag unsupported AI conclusions.','Identify conflicts between the company website and external sources.','Warn when information may be outdated.','Route uncertain or low-quality results for human review.','Include a clear source list in the final report.'];
const PLANNED_SV=['Samla information från den officiella webbplatsen och utvalda externa källor.','Filtrera irrelevanta och dubbla sökresultat.','Behåll de mest användbara källorna för analys.','Spara källtitlar, URL:er, datum och källtyp.','Koppla viktiga påståenden i rapporten till stödjande källor.','Markera AI-slutsatser som saknar stöd.','Upptäck konflikter mellan företagets webbplats och externa källor.','Varna när information kan vara inaktuell.','Skicka osäkra eller svaga resultat till mänsklig granskning.','Lägg till en tydlig källista i slutrapporten.'];

function PlannedV2Section(){const{lang}=window.useApp();const c=END_COPY[lang],items=lang==='sv'?PLANNED_SV:PLANNED_EN;return <Shell tone="lightAlt" pad="lg" id="planned-v2"><div className="reveal-up" style={{maxWidth:760,marginBottom:40}}><window.Eyebrow dark={false}>{c.plannedEy}</window.Eyebrow><span className="mono-tag light" style={{borderColor:'var(--warning-500)',color:'var(--warning-500)'}}>{c.plannedBadge}</span><h2 style={{font:'var(--text-display-m)',margin:'18px 0'}}>{c.plannedTitle}</h2><p style={{font:'var(--text-body-l)'}}>{c.plannedText}</p></div><div className="reveal-up" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:14}}>{items.map((x,i)=><div key={x} style={{padding:'18px 20px',background:'#fff',border:'1px dashed var(--border-default)',borderRadius:'var(--radius-m)',display:'flex',gap:14}}><span style={{color:'var(--warning-500)'}}>0{i+1}</span><span>{x}</span></div>)}</div><p style={{marginTop:26,color:'var(--text-muted)'}}>{c.plannedNote}</p></Shell>}

function LearnedSection(){const{lang}=window.useApp();const c=END_COPY[lang];return <Shell tone="lightAlt" pad="md" id="learned"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:48}}><div className="reveal-up"><window.Eyebrow dark={false}>{c.learnedEy}</window.Eyebrow><blockquote style={{margin:0,font:'var(--text-heading-m)',lineHeight:1.5}}>{c.learnedQuote}</blockquote><p>{c.learnedText}</p></div><div className="reveal-up" style={{background:'#fff',border:'1px solid var(--border-subtle)',borderRadius:'var(--radius-l)',padding:'28px 30px'}}><strong>{c.transparency}</strong><p>{c.transparency1}</p><p>{c.transparency2}</p></div></div></Shell>}

function RelatedSection(){const{lang}=window.useApp();const c=END_COPY[lang];const items=[[c.c1,c.c1Text,'https://minaflow-888.github.io/lead-capture-fixed-preview/'],[c.c2,c.c2Text,'https://minaflow-888.github.io/order-handoff-preview/']];return <Shell tone="navy" pad="md" id="related"><SectionHead eyebrow={c.relatedEy} title={c.relatedTitle}/><div className="reveal-up" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:20}}>{items.map((r,i)=><a key={r[0]} href={r[2]} className="panel-dark hover-lift" style={{display:'block',padding:'30px 32px',textDecoration:'none'}}><span className="mono-tag">CASE STUDY 0{i+1}</span><h3 style={{color:'var(--text-on-dark)'}}>{r[0]}</h3><p style={{color:'var(--text-on-dark-muted)'}}>{r[1]}</p><strong>{c.action} →</strong></a>)}</div></Shell>}

function FinalCTA(){const{lang}=window.useApp();const c=END_COPY[lang];return <Shell tone="ink" grid pad="lg"><div className="reveal-up" style={{maxWidth:760,margin:'0 auto',textAlign:'center'}}><window.Eyebrow>{c.ctaEy}</window.Eyebrow><h2 style={{font:'var(--text-display-m)',color:'var(--text-on-dark)'}}>{c.ctaTitle}</h2><p style={{font:'var(--text-body-l)',color:'var(--text-on-dark-muted)'}}>{c.ctaText}</p><div style={{marginTop:28}}><Button variant="primary" size="lg" href={V2_PORTFOLIO_URL}>{c.ctaBtn}</Button></div></div></Shell>}

function Footer(){const{lang}=window.useApp();const c=END_COPY[lang];return <footer style={{background:'var(--ink-950)',borderTop:'1px solid rgba(255,255,255,.08)',padding:'24px 28px',textAlign:'center',color:'var(--gray-500)',font:'var(--text-body-s)'}}>{c.footer}</footer>}

Object.assign(window,{StatesSection,PlannedV2Section,LearnedSection,RelatedSection,FinalCTA,Footer});
