// Bilingual quality control, capabilities, stack and limitations.
const { Icon, Shell, SectionHead } = window;

const QUALITY_COPY = {
  en:{
    qEy:'Why quality control matters', qTitle:'Generating text is not the same as checking it.', qLede:'A separate scenario evaluates every analysis before anything moves forward. The quality check uses a second Groq call with a different prompt — one focused on evaluation, not generation.',
    too:'Too generic — does not continue', ready:'Ready to approve — continues', note:'This check reduces weak output. It does not guarantee factual accuracy, so important results should still be reviewed by a person before use.',
    tooList:['Repeats information that appears on many company websites','Lacks company-specific observations or context','Sounds useful but gives nothing concrete to act on','Does not continue to the final report'],
    readyList:['Uses specific information from the company website','Includes observations that go beyond the obvious','Follows the expected structure','Clear enough to be useful in the final report'],
    capEy:'Core capabilities', capTitle:'What the system actually does', caps:['Website content retrieval via HTTP','Company analysis generation','Separate quality check scenario','Approved / needs-improvement routing','Final master report creation','Supabase workflow state management'],
    stackEy:'Technology stack', stackTitle:'Four tools, four clear responsibilities',
    tools:[['Make.com','Connects and controls all three scenarios. Make routes records between states based on structured Groq output.','workflow','#7A2FF8'],['Supabase','Stores company records, analyses, quality feedback, final reports and workflow statuses.','database','#3ECF8E'],['HTTP','Retrieves content from the company website and passes it to Groq.','globe','#3B82C4'],['Groq','Used for company analysis, quality evaluation and final report generation.','cpu','#F0662A']],
    limEy:'Honest by design', limTitle:'What still needs improvement', limLabel:'Current limitations', nextLabel:'Possible next steps',
    limits:['AI output can still contain weak or incorrect conclusions even after the quality check.','Website content may be incomplete, require JavaScript or block automated retrieval.','The quality check reduces generic output but does not replace human review.','Record locking reduces duplicate processing but is not a guaranteed safeguard in every edge case.','Production use would require stronger error handling, retry logic, source tracking and monitoring.','This is a portfolio demonstration tested with demonstration data, not a production deployment.'],
    next:['Add multi-source research using a search API alongside the company website','Include source references so claims can be traced back','Add retry and error handling for failed HTTP requests or Groq calls','Add a human review step before the final report is marked complete','Test with a broader range of company websites','Add conflict detection when external sources contradict the company website']
  },
  sv:{
    qEy:'Varför kvalitetskontroll behövs', qTitle:'Att generera text är inte samma sak som att kontrollera den.', qLede:'Ett separat scenario bedömer varje analys innan något går vidare. Kvalitetskontrollen använder ett andra Groq-anrop med en annan prompt — fokuserad på bedömning, inte generering.',
    too:'För generell — går inte vidare', ready:'Redo att godkännas — går vidare', note:'Kontrollen minskar svag output men garanterar inte fakta. Viktiga resultat bör fortfarande granskas av en person innan de används.',
    tooList:['Upprepar information som finns på många företagswebbplatser','Saknar företagsspecifika observationer eller sammanhang','Låter användbar men ger inget konkret att agera på','Går inte vidare till slutrapporten'],
    readyList:['Använder specifik information från företagets webbplats','Innehåller observationer som går längre än det uppenbara','Följer den förväntade strukturen','Är tillräckligt tydlig för att användas i slutrapporten'],
    capEy:'Kärnfunktioner', capTitle:'Vad systemet faktiskt gör', caps:['Hämtar webbplatsinnehåll via HTTP','Skapar företagsanalys','Separat scenario för kvalitetskontroll','Routing till approved / needs improvement','Skapar slutlig masterrapport','Hanterar arbetsflödets status i Supabase'],
    stackEy:'Teknikstack', stackTitle:'Fyra verktyg, fyra tydliga ansvarsområden',
    tools:[['Make.com','Kopplar ihop och styr alla tre scenarier. Make routar poster mellan statusar utifrån strukturerad Groq-output.','workflow','#7A2FF8'],['Supabase','Lagrar företagsposter, analyser, kvalitetsfeedback, slutrapporter och statusar.','database','#3ECF8E'],['HTTP','Hämtar innehåll från företagets webbplats och skickar det vidare till Groq.','globe','#3B82C4'],['Groq','Används för företagsanalys, kvalitetsbedömning och slutrapport.','cpu','#F0662A']],
    limEy:'Ärlig från början', limTitle:'Vad som fortfarande behöver förbättras', limLabel:'Nuvarande begränsningar', nextLabel:'Möjliga nästa steg',
    limits:['AI-output kan fortfarande innehålla svaga eller felaktiga slutsatser efter kvalitetskontrollen.','Webbplatsinnehåll kan vara ofullständigt, kräva JavaScript eller blockera automatisk hämtning.','Kvalitetskontrollen minskar generell output men ersätter inte mänsklig granskning.','Postlåsning minskar dubbla körningar men är inte ett garanterat skydd i alla specialfall.','Produktionsanvändning skulle kräva bättre felhantering, retry-logik, källspårning och övervakning.','Detta är en portfoliodemonstration testad med demodata, inte en produktionslösning.'],
    next:['Lägg till research från flera källor med en sök-API utöver företagets webbplats','Lägg till källhänvisningar så påståenden kan spåras','Lägg till retry- och felhantering för misslyckade HTTP- eller Groq-anrop','Lägg till mänsklig granskning innan slutrapporten markeras som klar','Testa fler typer av företagswebbplatser','Lägg till konfliktdetektering när externa källor motsäger företagets webbplats']
  }
};

function QualitySection(){const{lang}=window.useApp();const c=QUALITY_COPY[lang];return <Shell tone="lightAlt" pad="lg" id="quality"><SectionHead dark={false} center eyebrow={c.qEy} title={c.qTitle} lede={c.qLede}/><div className="reveal-up" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:24,maxWidth:940,margin:'0 auto'}}><div style={{background:'#fff',border:'1px solid var(--border-subtle)',borderRadius:'var(--radius-l)',padding:'30px 32px'}}><h3 style={{color:'var(--danger-500)'}}>{c.too}</h3><ul>{c.tooList.map(x=><li key={x}>{x}</li>)}</ul></div><div style={{background:'#fff',border:'1px solid var(--brand-300)',borderRadius:'var(--radius-l)',padding:'30px 32px'}}><h3 style={{color:'var(--success-500)'}}>{c.ready}</h3><ul>{c.readyList.map(x=><li key={x}>{x}</li>)}</ul></div></div><p className="reveal-up" style={{font:'var(--text-body-s)',color:'var(--text-muted)',textAlign:'center',maxWidth:640,margin:'36px auto 0'}}>{c.note}</p></Shell>}

function CapabilitiesSection(){const{lang}=window.useApp();const c=QUALITY_COPY[lang];const icons=['globe','file-text','badge-check','split','file-output','database'];return <Shell tone="ink" pad="md" id="capabilities"><SectionHead eyebrow={c.capEy} title={c.capTitle}/><div className="reveal-up" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:16}}>{c.caps.map((x,i)=><div key={x} className="panel-dark" style={{padding:'22px 24px',display:'flex',gap:16,alignItems:'center'}}><Icon name={icons[i]} size={20} color="var(--brand-400)"/><span style={{fontWeight:600,color:'var(--text-on-dark)'}}>{x}</span></div>)}</div></Shell>}

function StackSection(){const{lang}=window.useApp();const c=QUALITY_COPY[lang];return <Shell tone="navy" pad="md" id="stack"><SectionHead eyebrow={c.stackEy} title={c.stackTitle}/><div className="reveal-up" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:16}}>{c.tools.map(t=><div key={t[0]} className="panel-dark" style={{padding:26}}><div style={{display:'flex',alignItems:'center',gap:12,marginBottom:12}}><Icon name={t[2]} size={19} color={t[3]}/><strong style={{color:'var(--text-on-dark)'}}>{t[0]}</strong></div><p style={{margin:0,color:'var(--text-on-dark-muted)'}}>{t[1]}</p></div>)}</div></Shell>}

function LimitationsSection(){const{lang}=window.useApp();const c=QUALITY_COPY[lang];return <Shell tone="light" pad="lg" id="limitations"><SectionHead dark={false} eyebrow={c.limEy} title={c.limTitle}/><div className="reveal-up" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:48}}><div><h3>{c.limLabel}</h3>{c.limits.map(x=><div key={x} style={{padding:'12px 0',borderBottom:'1px solid var(--border-subtle)'}}>{x}</div>)}</div><div><h3>{c.nextLabel}</h3>{c.next.map((x,i)=><div key={x} style={{padding:'12px 0',borderBottom:'1px solid var(--border-subtle)',display:'flex',gap:12}}><span style={{color:'var(--brand-500)'}}>0{i+1}</span><span>{x}</span></div>)}</div></div></Shell>}

Object.assign(window,{QualitySection,CapabilitiesSection,StackSection,LimitationsSection});
